In [192]:
import pandas as pd
from urllib.parse import unquote

df = pd.read_json('data.json',encoding='utf-8')
#df.drop(['date','body','author','url'],axis=1,inplace=True) #for test_2.json
#df.drop(['id','news_content','date','url'],axis=1,inplace=True)

In [193]:
df['category'] = df['category'].apply(unquote)

In [185]:
df['category']

id                                         news_topic  \
0      1  เปิดใจ"อนุทิน ชาญวีรกูล"หัวหน้าพรรคภูมิใจไทย ป...   
1      2  "อนุทิน"เตรียมผลักดันสนามบินสตูลและสะพานถนนสตู...   
2      3  'อภิสิทธิ์​'เผยเพิ่งคุยไลน์ขำๆ กับ'อนุทิน​'เรื...   
3      4   "อนุทิน"เผย นายกฯ บรรจุกัญชาเป็นนโยบายรัฐบาลแล้ว   
4      5       "อนุทิน"ไม่ติดใจลงโทษสิริพงษ์ โหวตสวนมติพรรค   
..   ...                                                ...   
814  818  เห็นแล้วหวาดเสียว รวมคุณแม่ดารา โดนชาวเน็ตดราม...   
815  819  จินตหรา สุดช็อก เปิดใจคุณแม่จากไปต่อหน้า หัวใจ...   
816  820  มีลูกก็ยังแซ่บ! ชมภาพเด็ดเซ็กซี่ของคุณแม่ในวงก...   
817  821  เจนี่-มิกกี้ เผยภาพครอบครัวพร้อมหน้าครั้งแรก แ...   
818  822  หม่อมเอ็ม สุดอาลัยสูญเสียคุณแม่ด้วยโรคมะเร็งต่...   

                                          news_content                 date  \
0    สัมภาษณ์ อนุทิน ชาญวีรกูล ส.ส.บัญชีรายชื่อและห...  2019-06-10 12:53:05   
1    นายอนุทิน ชาญวีระกูล หัวหน้าพรรคภูมิใจไทย ลงพื...  2019-06-14 08:02:31   
2    จากกรณีกระแสข่าวพรรคอนาคตใหม่ อาจเสนอชื่อ นายอ...  2019-05-12 14:28:52   
3    พรรคภูมิใจไทยจัดสัมนาใหญ่ มั่นใจแนวทางกัญชาเสร...  2019-07-12 16:02:09   
4    ส.ส.ศรีสะเกษ พรรคภูมิใจไทย ยอมรับเครียด หลังโห...  2019-06-06 15:39:40   
..                                                 ...                  ...   
814  เพราะเทรนด์การรักสุขภาพกำลังมาแรง ทำให้คนส่วนใ...  2019-06-16 10:30:00   
815  นักร้องชื่อดัง จินตหรา พูนลาภ ได้สูญเสียคุณแม่...  2019-05-15 16:15:00   
816  ถึงแม้จะเป็นคุณแม่แล้ว หากแบ่งเวลาสักนิดเพื่ออ...  2019-06-15 09:30:00   
817  เพิ่งมีสมาชิกคนใหม่ตัวน้อยๆ ลืมตาดูโลกมาได้ไม่...  2019-12-10 15:53:00   
818  เป็นความสูญเสียอย่างมาก สำหรับครอบครัวของ หม่อ...  2019-08-18 18:20:00   

            author                                                url  \
0              ch3         http://news.ch3thailand.com/politics/96958   
1              ch3         http://news.ch3thailand.com/politics/97229   
2              ch3         http://news.ch3thailand.com/politics/94760   
3              ch3         http://news.ch3thailand.com/politics/99272   
4              ch3         http://news.ch3thailand.com/politics/96733   
..             ...                                                ...   
814  ไทยรัฐออนไลน์  https://www.thairath.co.th/entertain/news/1592640   
815  ไทยรัฐออนไลน์  https://www.thairath.co.th/entertain/news/1568261   
816  ไทยรัฐออนไลน์  https://www.thairath.co.th/entertain/news/1591266   
817  ไทยรัฐออนไลน์  https://www.thairath.co.th/entertain/news/1722951   
818  ไทยรัฐออนไลน์  https://www.thairath.co.th/entertain/news/1640428   

     category  
0    politics  
1    politics  
2    politics  
3    politics  
4    politics  
..        ...  
814      news  
815      news  
816      news  
817      news  
818      news  

[819 rows x 7 columns]

In [194]:
train = df[df['author']=='ch3']
test = df[df['author']=='ไทยรัฐออนไลน์']
X_train, y_train = train['news_topic'],train['category']
X_test, y_test = test['news_topic'],test['category']

In [195]:
import numpy as np

In [196]:
X_train = np.array([title for title in X_train])

In [197]:
import re
#prepare each sentence
def text_prepare(text):
    text = re.sub("[/(){}\[\]\|@,;\n\t:\'\- ]", '', text)
    text = re.sub("[/\xa0]", '', text)
    return text

In [198]:
X_train = np.array([text_prepare(title) for title in X_train])

In [199]:
type(X_train)

numpy.ndarray

In [200]:
X_train

array(['เปิดใจ"อนุทินชาญวีรกูล"หัวหน้าพรรคภูมิใจไทยปมเก้าอี้รัฐมนตรีใช้ดีลเดิม',
       '"อนุทิน"เตรียมผลักดันสนามบินสตูลและสะพานถนนสตูลเปอร์ลิส',
       'อภิสิทธิ์\u200bเผยเพิ่งคุยไลน์ขำๆกับอนุทิน\u200bเรื่อง\u200bกระแสข่าวณัฏฐพลเผยมีพรรคร่วมรัฐบาลแล้ว20พรรค',
       '"อนุทิน"เผยนายกฯบรรจุกัญชาเป็นนโยบายรัฐบาลแล้ว',
       '"อนุทิน"ไม่ติดใจลงโทษสิริพงษ์โหวตสวนมติพรรค',
       'อนุทินโพสต์ภาพนั่งไหว้พระบอก"ชาติศาสนาพระมหากษัตริย์ประชาชนไปทางนี้แหละไม่มีหลงทาง"',
       'อนุทินพร้อมเป็นฝ่ายค้านถ้ารัฐบาลไม่เอากัญชา',
       'อนุทินโต้ข่าวลือยันยังไม่จับมือขั้วพปชร.ขอคิดรอบคอบหากใครยังไม่พอใจครั้งหน้าไม่ต้องเลือก',
       '"อนุทิน"ลั่นได้ปลูกกัญชาบ้านละ6ต้นแน่',
       '"อนุทิน"ส่งรายชื่อครม.ถึงมือนายกฯพรุ่งนี้',
       'ภูมิใจไทยประชุมใหญ่จ่อเลือก"อนุทิน"นั่งหัวหน้าพรรคต่อ',
       '"อนุทิน"เรียกส.ส.ศรีสะเกษยกมือสวนมติพรรคงดออกเสียงเลือก"ประยุทธ์"เป็นนายกฯ',
       'มติภูมิใจไทยให้อนุทินประสานตั้งรัฐบาลยันอยู่ฝ่ายเสียงข้างมาก',
       'ภูมิใจไทยเห็นตรงกันชู"อนุทิน"บัญชีนายกฯเบอร์เดียว',


### Bag of words

In [201]:
from pythainlp.tokenize import word_tokenize

In [202]:

#tokenize function
def Thaitokenize(text):
    """
    turn a Thai sentence into Thai words with meaning
    """
    text = ''.join(text.split('"')) ##handled in regex??
    text = word_tokenize(text , engine = 'pyicu')
    return text

In [203]:
#try mapping function
#Error
#list(map(Thaitokenize,X_train))

In [204]:
Thaitokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียมในฐานะบริษัทแรกในไทยที่ได้ร่วมลงนามในสัญญา UN Global Standards of Conduct for Business\xa0')

['แสน',
 'สิริ',
 'สร้าง',
 'มาตรฐาน',
 'ใหม่',
 'ของ',
 'การ',
 'ยอมรับ',
 'ความเท่าเทียม',
 'ใน',
 'ฐานะ',
 'บริษัท',
 'แรก',
 'ใน',
 'ไทย',
 'ที่',
 'ได้',
 'ร่วม',
 'ลงนาม',
 'ใน',
 'สัญญา',
 ' ',
 'UN',
 ' ',
 'Global',
 ' ',
 'Standards',
 ' ',
 'of',
 ' ',
 'Conduct',
 ' ',
 'for',
 ' ',
 'Business',
 '\xa0']

### just a test for fun###
%timeit word_tokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียม' , engine = 'pyicu')

### just a test for fun###
%timeit word_tokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียม' , engine = 'newmm')

In [205]:
#words to account in the bag
words_counts = {}

for i in X_train: #each i is a topic sentence
    wordlist = Thaitokenize(i)
    for j in wordlist:
        words_counts[j] = words_counts.get(j,0) + 1
#words_counts = 238

WORDS_TO_INDEX = dict(zip(words_counts.keys(),list(x for x in range(len(words_counts)))))

In [206]:
len(words_counts)

1306

In [207]:
#create a bag of words for a sentence
def my_bag_of_words(text, words_to_index, dict_size):
    """
        text: a sentence
        words_to_index: words to count in the bag 
        e.g.
        words_to_index = {'hi': 0, 'you': 1, 'me': 2, 'are': 3}
        
        dict_size: size of the dictionary
        
        return a vector which is a bag-of-words representation of 'text'
    """
    result_vector = np.zeros(dict_size)
    
    #tokenize Thai words
    words = Thaitokenize(text)
    
    for i in words:
      if(words_to_index.get(i,-1)!=-1) :
        result_vector[words_to_index[i]]=+1
    return result_vector

In [208]:
X_train_my_bag = np.array([my_bag_of_words(text, WORDS_TO_INDEX, len(words_counts)) for text in X_train])

In [209]:
# [word for word in WORDS_TO_INDEX]
type(WORDS_TO_INDEX.keys())

dict_keys

In [210]:
#for illustration & checking
myBagX = pd.DataFrame(X_train_my_bag,columns = WORDS_TO_INDEX.keys())
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
#myBagX

In [178]:
myBagX

เปิดใจ  อนุทิน  ชาญ  วีร   กู    ล  หัวหน้าพรรค  ภูมิใจ  ไทย   ปม  \
0       1.0     1.0  1.0  1.0  1.0  1.0          1.0     1.0  1.0  1.0   
1       0.0     1.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
2       0.0     1.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
3       0.0     1.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
4       0.0     1.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
..      ...     ...  ...  ...  ...  ...          ...     ...  ...  ...   
180     0.0     0.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
181     0.0     0.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
182     0.0     0.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
183     0.0     0.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   
184     0.0     0.0  0.0  0.0  0.0  0.0          0.0     0.0  0.0  0.0   

     เก้าอี้  รัฐมนตรี  ใช้  ดีล  เดิม  เตรียม  ผลักดัน  สนามบิน  สตูล  และ  \
0        1.0       1.0  1.0  1.0   1.0     0.0      0.0      0.0   0.0  0.0   
1        0.0       0.0  0.0  0.0   0.0     1.0      1.0      1.0   1.0  1.0   
2        0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
3        0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
4        0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
..       ...       ...  ...  ...   ...     ...      ...      ...   ...  ...   
180      0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
181      0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
182      0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
183      0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   
184      0.0       0.0  0.0  0.0   0.0     0.0      0.0      0.0   0.0  0.0   

     สะพาน  ถนน  เปอร์   ลิ    ส  อภิสิทธิ์    ​  เผย  เพิ่ง  คุย  ไลน์   ขำ  \
0      0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
1      1.0  1.0    1.0  1.0  1.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
2      0.0  0.0    0.0  0.0  0.0        1.0  1.0  1.0    1.0  1.0   1.0  1.0   
3      0.0  0.0    0.0  0.0  0.0        0.0  0.0  1.0    0.0  0.0   0.0  0.0   
4      0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
..     ...  ...    ...  ...  ...        ...  ...  ...    ...  ...   ...  ...   
180    0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
181    0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
182    0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
183    0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   
184    0.0  0.0    0.0  0.0  0.0        0.0  0.0  0.0    0.0  0.0   0.0  0.0   

       ๆ  กับ  เรื่อง  กระแสข่าว  ณัฏฐพล   มี  พรรคร่วมรัฐบาล  แล้ว   20  \
0    0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
1    0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
2    1.0  1.0     1.0        1.0     1.0  1.0             1.0   1.0  1.0   
3    0.0  0.0     0.0        0.0     0.0  0.0             0.0   1.0  0.0   
4    0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
..   ...  ...     ...        ...     ...  ...             ...   ...  ...   
180  0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
181  0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
182  0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
183  0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   
184  0.0  0.0     0.0        0.0     0.0  0.0             0.0   0.0  0.0   

     พรรค  นายกฯ  บรรจุ  กัญชา  เป็น  นโยบาย  รัฐบาล  ไม่  ติดใจ  ลงโทษ  สิริ  \
0     0.0    0.0    0.0    0.0   0.0     0.0     0.0  0.0    0.0    0.0   0.0   
1     0.0    0.0    0.0    0.0   0.0     0.0     0.0  0.0    0.0    0.0   0.0   
2     1.0    0.0    0.0    0.0   0.0     0.0     0

In [179]:
#turn y values to 1s,0s

In [211]:
# from sklearn.preprocessing import MultiLabelBinarizer
# this is for list of tags

In [219]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
#lb.fit_transform([1, 2, 6, 4, 2]) 
#fit & transform in one step
#fit = figure out different classes and turn into necessary binary formats
#transform = transform given data into binary formats

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])

In [225]:
y_train_lb = lb.fit_transform(y_train)


In [263]:
lb.classes_.size

17

In [233]:
#for illustration & checking
Y_LB = pd.DataFrame(y_train_lb,columns = lb.classes_)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
Y_LB.iloc[10:20]
#y_train.iloc[10:20]

10        politics
11        politics
12        politics
13        politics
14        ข่าวด่วน
15        politics
16        politics
17    ข่าวการเมือง
18        politics
19        politics
Name: category, dtype: object

In [236]:
y_train_lb.shape

(185, 17)

In [238]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
#example
X = np.array([
     [10, 10],
     [8, 10],
     [-5, 5.5],
     [-5.4, 5.5],
     [-20, -20],
     [-15, -20]])
y = np.array([0, 0, 1, 1, 2, 2])
clf = OneVsRestClassifier(SVC()).fit(X, y)
clf.predict([[-19, -20], [9, 9], [-5, 5]])

array([2, 0, 1])

In [240]:
clf = OneVsRestClassifier(SVC()).fit(X_train_my_bag, y_train)

In [249]:
y_train = np.array(y_train)

In [250]:
#check the predictions, models applied correctly? Yes
y = clf.predict(X_train_my_bag)
print(np.concatenate((y.reshape(len(y),1), y_train.reshape(len(y_train),1)),1))

[['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['ข่าวด่วน' 'ข่าวด่วน']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'ข่าวการเมือง']
 ['politics' 'politics']
 ['politics' 'politics']
 ['ข่าวการเมือง' 'ข่าวการเมือง']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['politics' 'politics']
 ['entertainment' 'entertainment']
 ['abroad' 'abroad']
 ['entertainment' 'entertainment']
 ['local' 'local']
 ['politics' 'politics']
 ['ข่าวการเมือง' 'ข่าวการเมือง']
 ['ข่าวด่วน' 'ข่าวด่วน']
 ['ข่าวต่างประเทศ' 'ข่าวต่างประเทศ']
 ['index.php' 'index.php']
 ['local' 'local']
 ['ข่าวต่างประเทศ' 'ข่าวต่างประเทศ']
 ['ข่าวกีฬา' 'ข่าวกีฬา']


In [257]:
X_test = np.array([text_prepare(title) for title in X_test])
X_test_my_bag = np.array([my_bag_of_words(text, WORDS_TO_INDEX, len(words_counts)) for text in X_test])
y_pred = clf.predict(X_test_my_bag)
y_test = np.array(y_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#print(np.concatenate(y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1),1))

[['politics' 'politic']
 ['politics' 'politic']
 ['politics' 'local']
 ['entertainment' 'politic']
 ['politics' 'local']
 ['politics' 'politic']
 ['entertainment' 'politic']
 ['politics' 'local']
 ['entertainment' 'politic']
 ['politics' 'politic']
 ['politics' 'politic']
 ['politics' 'local']
 ['politics' 'politic']
 ['politics' 'politic']
 ['entertainment' 'politic']
 ['politics' 'politic']
 ['politics' 'politic']
 ['entertainment' 'politic']
 ['politics' 'politic']
 ['politics' 'local']
 ['politics' 'local']
 ['entertainment' 'politic']
 ['politics' 'local']
 ['entertainment' 'politic']
 ['politics' 'politic']
 ['politics' 'local']
 ['politics' 'politic']
 ['entertainment' 'politic']
 ['politics' 'society']
 ['politics' 'local']
 ['politics' 'politic']
 ['politics' 'local']
 ['politics' 'politic']
 ['entertainment' 'politic']
 ['politics' 'society']
 ['politics' 'politic']
 ['politics' 'politic']
 ['politics' 'local']
 ['politics' 'politic']
 ['entertainment' 'politic']
 ['politics'

In [259]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  7  0  0  0 10  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 11  0  0  0 13  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0  0 42  0  0  0 26  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0

0.10268948655256724

In [262]:
test = text_prepare('“อนุทิน” ขอ ผู้ร้อง เปิดชื่อ อักษรย่อ \"พ\" คนหักหัวคิวโรงแรม 40%')
test = np.array([my_bag_of_words(test, WORDS_TO_INDEX, len(words_counts))])
clf.predict(test)

array(['politics'], dtype='<U21')