# From Prev.
#Rearranged code
#Used larger training set
#Match Similar words manually (due to limited size of categories [hopefully :P])
#text = re.sub("[^ก-๛]", '', text) 47.34% with TFIDF
#text = re.sub("[^ก-ไ๐-๙]", '', text) 48.44% with TFIDF
#text = re.sub("[^ก-ไ๐-๙‘’“”]", '', text) 48.99% with TFIDF
#used news_content instead of news_label, pretty fast, 61.83%

In [19]:
import pandas as pd
from urllib.parse import unquote

df = pd.read_json('data-1.json',encoding='utf-8')
#df.drop(['date','body','author','url'],axis=1,inplace=True) #for test_2.json
#df.drop(['id','news_content','date','url'],axis=1,inplace=True)

In [20]:
CAT= {
    #category: change to this
    'ข่าวบันเทิง':"entertainment",
    'regional':'local',
    'sport':'sports',
    'ข่าวกีฬา':'sports',
    'ข่าวอาชญากรรม':'crime',
    'khrongkhaidaasapparod':'ข่าวโครงข่ายตาสับปะรด',
    'around-the-world-news':'foreign',
    'abroad':'foreign',
    'ข่าวต่างประเทศ':'foreign',
    'ข่าวไลฟ์สไตล์':'lifestyle',
    'analysis-today-politics':'politics',
    'politic':'politics',
    'ข่าวเศรษฐกิจ':'economics',
    'economy':'economics',
    'economic':'economics',
    'uncategorized':'others',
    'auto':'car-vehicle',
    'thai-soccer':'thaifootball',
    'ข่าวพระราชสำนัก':'royalnews',
    'it':'tech'
}

In [21]:
def conv_cate(category):
    result = CAT.get(category,-1)
    if result!=-1:
        return result
    else :
        #in case want to update dictionary
        #CAT[category] = category
        return category

In [22]:
df['category'] = df['category'].apply(unquote).apply(conv_cate)

In [23]:
#tags cleaning
#df[df['category']=='1293427']
#df.drop([292],inplace=True)
df['category'].unique()
len(df['category'].unique())

53

In [24]:
df.isnull().sum()
#df.dropna().reset_index(drop=True)

id              0
news_topic      0
news_content    0
date            0
author          0
url             0
category        0
dtype: int64

In [25]:
import numpy as np
category = np.array(df['category'])
tags, freq = np.unique(category,return_counts=True)
freqList = list(zip(tags,freq))
freqList.sort(key=lambda elem:elem[1]) #sort by frequency
freqList[20:]

[('car-vehicle', 5),
 ('stock-monitor', 5),
 ('thaifootball', 6),
 ('covid-19', 7),
 ('index.php', 7),
 ('ข่าวโครงข่ายตาสับปะรด', 9),
 ('life', 10),
 ('women', 14),
 ('ข่าวในประเทศ', 14),
 ('bangkok', 15),
 ('bbc-thai', 18),
 ('trcheerthai', 18),
 ('special-stories', 20),
 ('society', 21),
 ('lifestyle', 22),
 ('tech', 22),
 ('breaking-news', 23),
 ('ข่าวด่วน', 23),
 ('pr-news', 28),
 ('news', 29),
 ('education', 30),
 ('others', 31),
 ('around-thailand', 32),
 ('business', 34),
 ('eurofootball', 78),
 ('crime', 80),
 ('economics', 96),
 ('article', 98),
 ('entertainment', 129),
 ('sports', 257),
 ('politics', 261),
 ('foreign', 338),
 ('local', 357)]

In [26]:
df.head(1)

id                                         news_topic  \
0   1  "นกเอี้ยง จันทิมา"โดนหนุ่มจับก้น เจ้าตัวตบสวนถ...   

                                        news_content                 date  \
0  นกเอี้ยง จันทิมา นักร้องสาว โพสต์เฟสบุ๊กส่วนตั...  2019-06-29 18:30:44   

  author                                              url       category  
0    ch3  http://news.ch3thailand.com/entertainment/98347  entertainment

In [27]:

X = np.array(df['news_content'])
y = np.array(df['category'])

# Cleaning text


In [ ]:
re.sub("[^ก-๙‘’“”]", '', 'ฟหกดเ้่าสาสงๆไำพัีนรนบลผปแอิืมทมใฝๅ/_ภถุึคึre.sub("[^ก-ไ๐-๙‘’“”]"ฟหกดเ้่าสาสงๆไำพัีนรนบลผปแอิืมคตจจตช!!!')
#after searching thai ascii

In [28]:
import re
#prepare each sentence
def text_prepare(text):
    #text = re.sub("[/(){}\[\]\|@,;\n\t:\'\-!,'์'‘’“”]", '', text)
    #text = re.sub("[/\xa0]", '', text)
    #text = re.sub("[0-9]", '', text)
    text = re.sub("[^ก-๙‘’“”]", '', text)
    return text

In [29]:
#execute prepare
X = np.array([text_prepare(body) for body in X])

# Prepare train and test set

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [31]:
type(X_train)

numpy.ndarray

In [32]:
len(X_test)

545

## Check tag distribution

In [ ]:
#not well distributed
tags, freq = np.unique(y_train,return_counts=True)
list(zip(tags,freq))

# Tokenize thai words

In [33]:
from pythainlp.tokenize import word_tokenize

In [34]:

#tokenize function
def Thaitokenize(text):
    """
    turn a Thai sentence into Thai words with meaning
    """
    text = ''.join(text.split('"')) ##handled in regex??
    text = word_tokenize(text , engine = 'pyicu')
    return text

In [ ]:
#try mapping function
#Error
#list(map(Thaitokenize,X_train))

In [35]:
Thaitokenize('แสนสิริสร้างUN Global Standards of Conduct for Business\xa0')

['แสน',
 'สิริ',
 'สร้าง',
 'UN',
 ' ',
 'Global',
 ' ',
 'Standards',
 ' ',
 'of',
 ' ',
 'Conduct',
 ' ',
 'for',
 ' ',
 'Business',
 '\xa0']

### just a test for fun###
%timeit word_tokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียม' , engine = 'pyicu')

### just a test for fun###
%timeit word_tokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียม' , engine = 'newmm')

# Gensim

In [36]:
X_train

array(['โรงเรียนวัดครึ่งใต้จเชียงรายเป็นโรงเรียนพระปริยัติธรรมที่ได้นำหลักสูตรภาษาอังกฤษเข้ามาสอนแต่การสอนที่นี่ไม่เหมือนที่อื่นคือมีพระสงฆ์ที่สอนได้อย่างสนุกทำให้นักเรียนพระสามารถพูดอ่านภาษาอังกฤษได้เร็ว',
       'ใหม่สุคนธวาทำชาวเน็ตและแฟนคลับแฮปปี้สุดๆหลังประกาศข่าวดีผ่านไอจีส่วนตัวตอนนี้ท้องแล้วแถมเป็นวิธีธรรมชาติด้วย',
       'ครมโยกสลับเก้าอี้อธิบดีปภโยธาฯตั้งผู้ว่าฯผู้ตรวจการมทศาลพิพากยกฟ้องมจจุลเจิมกรณีหมิ่นประมาทพรรคอนาคตใหม่ล้มเจ้าลาภลอยแม่เฒ่านั่งคุยเพื่อนบ้านมีแม่ค้านำลอตเตอรี่มาขายชุดใบแต่เงินไม่พอซื้อได้ใบเดียวอีกใบเพื่อนซื้อถูกรางวัลที่ทั้งคู่รับคนละล้านครมโยกสลับเก้าอี้อธิบดีปภโยธาฯตั้งผู้ว่าฯผู้ตรวจการมทศาลพิพากยกฟ้องมจจุลเจิมกรณีหมิ่นประมาทพรรคอนาคตใหม่ล้มเจ้าลาภลอยแม่เฒ่านั่งคุยเพื่อนบ้านมีแม่ค้านำลอตเตอรี่มาขายชุดใบแต่เงินไม่พอซื้อได้ใบเดียวอีกใบเพื่อนซื้อถูกรางวัลที่ทั้งคู่รับคนละล้านครมโยกสลับเก้าอี้อธิบดีปภโยธาฯตั้งผู้ว่าฯผู้ตรวจการมทครมโยกมณฑลนั่งอธิบดีปภให้ชยพลสลับนั่งคุมโยธาฯตั้งชัยสิทธิ์รองผู้ว่าฯสุรินทร์นั่งพ่อเมืองยะลาสมเจตน์รองผู้ว่าฯเมืองกาญจน์ขึ้นเป็นผู้

In [38]:
sent = [Thaitokenize(row) for row in X_train]

In [39]:
from gensim.models.phrases import Phrases, Phraser
phrases = Phrases(sent, min_count=30, progress_per=10000)

In [40]:
phrases

In [41]:
bigram = Phraser(phrases)

In [43]:
sentences = bigram[sent]
list(sentences[0:2])

[['โรงเรียน',
  'วัด',
  'ครึ่ง',
  'ใต้',
  'จ',
  'เชียงราย',
  'เป็น',
  'โรงเรียน',
  'พระปริยัติธรรม',
  'ที่',
  'ได้',
  'นำ',
  'หลักสูตร',
  'ภาษาอังกฤษ',
  'เข้ามา',
  'สอน',
  'แต่',
  'การสอน',
  'ที่นี่',
  'ไม่',
  'เหมือน',
  'ที่อื่น',
  'คือ',
  'มี',
  'พระสงฆ์',
  'ที่',
  'สอน',
  'ได้',
  'อย่าง',
  'สนุก',
  'ทำให้',
  'นักเรียน',
  'พระ',
  'สามารถ',
  'พูด',
  'อ่าน',
  'ภาษาอังกฤษ',
  'ได้',
  'เร็ว'],
 ['ใหม่',
  'สุคนธ',
  'วา',
  'ทำ',
  'ชาว_เน็ต',
  'และ',
  'แฟนคลับ',
  'แฮปปี้',
  'สุด',
  'ๆ',
  'หลัง',
  'ประกาศ',
  'ข่าวดี',
  'ผ่าน',
  'ไอ',
  'จี',
  'ส่วนตัว',
  'ตอนนี้',
  'ท้อง',
  'แล้ว',
  'แถม',
  'เป็น',
  'วิธี',
  'ธรรมชาติ',
  'ด้วย']]

In [44]:
from collections import defaultdict 
word_freq = defaultdict(int)
for sent in sentences:
    for i in sent:
        word_freq[i] += 1
len(word_freq)

19505

In [45]:
sorted(word_freq, key=word_freq.get, reverse=True)[:10]

['ที่', 'และ', 'ใน', 'ของ', 'มี', 'ได้', 'การ', 'เป็น', 'จะ', 'ไม่']

# Train Word2Vec Model

In [47]:
import multiprocessing

from gensim.models import Word2Vec

In [ ]:
w2v_model1 = Word2Vec(min_count=20,
                     window=2,
                     size=300,
                     sample=6e-5, 
                     alpha=0.03, 
                     min_alpha=0.0007, 
                     negative=20,
                     workers=multiprocessing.cpu_count()-1)

In [ ]:
from time import time
import logging  # Setting up the loggings to monitor gensim
logging.basicConfig(format="%(levelname)s - %(asctime)s: %(message)s", datefmt= '%H:%M:%S', level=logging.INFO)

t = time()

w2v_model1.build_vocab(sentences, progress_per=10000)

print('Time to build vocab: {} mins'.format(round((time() - t) / 60, 2)))

In [ ]:

t = time()

w2v_model1.train(sentences, total_examples=w2v_model1.corpus_count, epochs=30, report_delay=1)

print('Time to train the model: {} mins'.format(round((time() - t) / 60, 2)))

In [ ]:
w2v_model1.init_sims(replace=True) #???

In [ ]:
w2v_model1.wv.most_similar(positive=["คำ"])

In [ ]:
w2v_model1.save("thaiwords1.model")

# Load pretrained model

In [48]:
model = Word2Vec.load("thaiwords1.model")

In [49]:
my_dict = dict({})
for idx, key in enumerate(model.wv.vocab):
    my_dict[key] = model.wv[key]

In [52]:
my_dict['โรงเรียน']

array([-0.00651663, -0.01781503, -0.11165202, -0.04425615, -0.00523276,
       -0.01081269,  0.0279975 ,  0.03115314,  0.05671701,  0.05039205,
       -0.00112414,  0.05193855,  0.05144665,  0.01242242, -0.11721922,
        0.05319424,  0.04598312, -0.04617419,  0.0480236 , -0.03745062,
       -0.11688701, -0.06541347, -0.13756381, -0.01895887,  0.08707064,
       -0.01644869, -0.00432686, -0.05448607, -0.13113332, -0.05959152,
        0.02334665, -0.0023897 , -0.01325766,  0.0159021 ,  0.04615885,
        0.0032223 ,  0.00454551, -0.03209181, -0.00313695,  0.0099358 ,
        0.03170666,  0.00319673,  0.00783641,  0.04308835,  0.14121616,
        0.0370038 , -0.04909885,  0.04557142,  0.07890169, -0.06877005,
       -0.05483996,  0.01914655,  0.03089308,  0.08278416,  0.02955536,
        0.06573854, -0.05773409, -0.01130446,  0.07606579,  0.05182923,
       -0.00785762,  0.0731385 ,  0.02010598,  0.04874031,  0.00242036,
        0.03519546, -0.12604634, -0.06595021,  0.01033402, -0.02

### words to account in the bag
words_counts = {}

for i in X_train: #each i is a topic sentence
    wordlist = Thaitokenize(i)
    for j in wordlist:
        words_counts[j] = words_counts.get(j,0) + 1
#words_counts = 238

WORDS_TO_INDEX = dict(zip(words_counts.keys(),list(x for x in range(len(words_counts)))))

### len(words_counts)

# Create bag of words

In [ ]:
#create a bag of words for a sentence
def my_bag_of_words(text, words_to_index, dict_size):
    """
        text: a sentence
        words_to_index: words to count in the bag 
        e.g.
        words_to_index = {'hi': 0, 'you': 1, 'me': 2, 'are': 3}
        
        dict_size: size of the dictionary
        
        return a vector which is a bag-of-words representation of 'text'
    """
    result_vector = np.zeros(dict_size)
    
    #tokenize Thai words
    words = Thaitokenize(text)
    
    for i in words:
      if(words_to_index.get(i,-1)!=-1) :
        result_vector[words_to_index[i]]=+1
    return result_vector

In [ ]:
#X_train_my_bag = np.array([my_bag_of_words(text, WORDS_TO_INDEX, len(words_counts)) for text in X_train])

# TFIDF

In [155]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [ ]:
#X_train_tfidf = vectorizer.fit_transform(X_train)
#print(vectorizer.get_feature_names())
#print(X.shape)

In [156]:
vectorizer = TfidfVectorizer(tokenizer=Thaitokenize, max_df=0.9, min_df = 5)
#vectorizer = TfidfVectorizer(tokenizer=Thaitokenize, max_df=0.9, min_df = 0)
#max_df=0.8, min_df=5 not much difference
#vectorizer = TfidfVectorizer(tokenizer=Thaitokenize, max_df=0.8, min_df = 10)
X_train_tfidf = vectorizer.fit_transform(X_train)
print(vectorizer.get_feature_names())
print(X_train_tfidf.shape)

['ก', 'กก', 'กค', 'กช', 'กซ์', 'กฎ', 'กฎระเบียบ', 'กฎหมาย', 'กฏ', 'กด', 'กดดัน', 'กต', 'กตัญญู', 'กติกา', 'กทม', 'กน', 'กนก', 'กนิษฐา', 'กบ', 'กบฏ', 'กป', 'กพ', 'กภจว', 'กม', 'กมล', 'กย', 'กร', 'กรกฎาคม', 'กรง', 'กรณี', 'กรณีพิเศษ', 'กรณีศึกษา', 'กรม', 'กรมการพัฒนาชุมชน', 'กรมการแพทย์', 'กรมชลประทาน', 'กรมประชาสัมพันธ์', 'กรมวิทยาศาสตร์การแพทย์', 'กรมอุตุนิยมวิทยา', 'กรร', 'กรรม', 'กรรมการ', 'กรรมการผู้จัดการ', 'กรรมาธิการ', 'กรวม', 'กรอ', 'กรอก', 'กรอง', 'กรอบ', 'กระ', 'กระจก', 'กระจาย', 'กระจายเสียง', 'กระจ่าง', 'กระชับ', 'กระชาก', 'กระดาษ', 'กระดูก', 'กระตุ้น', 'กระทบ', 'กระทรวง', 'กระทรวงกลาโหม', 'กระทรวงการคลัง', 'กระทรวงการต่างประเทศ', 'กระทรวงคมนาคม', 'กระทรวงพาณิชย์', 'กระทรวงมหาดไทย', 'กระทรวงยุติธรรม', 'กระทรวงศึกษาธิการ', 'กระทรวงสาธารณสุข', 'กระทรวงอุตสาหกรรม', 'กระทรวงเกษตรฯ', 'กระทรวงเกษตรและสหกรณ์', 'กระทั่ง', 'กระทำ', 'กระทำการ', 'กระทำความผิด', 'กระทิง', 'กระนั้น', 'กระบวน', 'กระบวนการ', 'กระบอก', 'กระบะ', 'กระบี่', 'กระสุน', 'กระเด็น', 'กระเป๋า', 'กระแทก', 'กระแส', 'ก

In [ ]:
#[word for word in WORDS_TO_INDEX]
#type(WORDS_TO_INDEX.keys())
#X_train_tfidf

##ARRAY <-> Sparse matrix much faster
#X_train_tfidf.toarray() 
#sparse matrix to array
#from scipy import sparse
#sparse.csr_matrix(X_train_tfidf.toarray()) 
#array to sparse matrix

In [ ]:
#for illustration & checking
featurelist = vectorizer.get_feature_names()
TFIDF = pd.DataFrame(X_train_tfidf.toarray(),columns = featurelist)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
#np.count_nonzero(TFIDF['กฎระเบียบ'].values) #6 occurences of กฎระเบียบ
TFIDF['กฎระเบียบ']

In [157]:
featurelist = vectorizer.vocabulary_
featurelist = {y:x for x,y in featurelist.items()}

# Test stuff

In [145]:
#get the vector for certain word
len(my_dict[featurelist[1879]])
#instead of my_dict['กช'] not found error
my_dict.get('กช',np.zeros(300))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [136]:
#test if temp can be turned into sparse matrix
temp =0
temp += X_train_tfidf.getcol(0).multiply(my_dict[featurelist[0]])
temp
#create 1st word-vector matrix for all sentences
print(X_train_tfidf.getcol(0).multiply(my_dict[featurelist[0]]))

<1635x300 sparse matrix of type '<class 'numpy.float64'>'
	with 21600 stored elements in COOrdinate format>

# TFIDF with word vec

In [158]:
#get each row, multiply by corresponding word vectors, store... slower???
#print(X_train_tfidf[1].nonzero()[1])

#get each word, multiply by corresponding vectors
#from scipy.sparse import csr_matrix
def tfidf_wordvec(tfidf):
    features = tfidf.shape[1]
    #get number of words/features
    result = 0
    for word in range(features):
        result += tfidf.getcol(word).multiply(my_dict.get(featurelist[word],np.zeros(300)))
        #multiply the tfidf by 0 if word does not exist in my_dict
    return result

In [160]:
X_train_tfidf = tfidf_wordvec(X_train_tfidf)

# turn y values to 1s,0s

In [ ]:
# from sklearn.preprocessing import MultiLabelBinarizer
# this is for list of tags

In [ ]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
#lb.fit_transform([1, 2, 6, 4, 2]) 
#fit & transform in one step
#fit = figure out different classes and turn into necessary binary formats
#transform = transform given data into binary formats

In [ ]:
y_train_lb = lb.fit_transform(y_train)


In [ ]:
lb.classes_.size

In [ ]:
#for illustration & checking
Y_LB = pd.DataFrame(y_train_lb,columns = lb.classes_)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
Y_LB.iloc[10:20]
#y_train.iloc[10:20]

In [ ]:
y_train_lb.shape

# Train model to predict tags

In [149]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
#example
X = np.array([
     [10, 10],
     [8, 10],
     [-5, 5.5],
     [-5.4, 5.5],
     [-20, -20],
     [-15, -20]])
y = np.array([0, 0, 1, 1, 2, 2])
clf = OneVsRestClassifier(SVC()).fit(X, y)
clf.predict([[-19, -20], [9, 9], [-5, 5]])

array([2, 0, 1])

In [161]:
clf = OneVsRestClassifier(SVC()).fit(X_train_tfidf, y_train)

In [152]:
y_train

array(['lifestyle', 'entertainment', 'local', ..., 'economics', 'crime',
       'bangkok'], dtype=object)

In [162]:
#check the predictions, models applied correctly? Yes
y = clf.predict(X_train_tfidf)
print(np.concatenate((y.reshape(len(y),1), y_train.reshape(len(y_train),1)),1))

[['lifestyle' 'lifestyle']
 ['entertainment' 'entertainment']
 ['sports' 'local']
 ...
 ['economics' 'economics']
 ['local' 'crime']
 ['politics' 'bangkok']]


In [164]:
X_test = np.array([text_prepare(title) for title in X_test])
#X_test_my_bag = np.array([my_bag_of_words(text, WORDS_TO_INDEX, len(words_counts)) for text in X_test])
X_test_tfidf = tfidf_wordvec(vectorizer.transform(X_test))
y_pred = clf.predict(X_test_tfidf)
y_test = np.array(y_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#print(np.concatenate(y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1),1))

[['foreign' 'economics']
 ['local' 'crime']
 ['foreign' 'foreign']
 ...
 ['local' 'local']
 ['politics' 'politics']
 ['foreign' 'foreign']]


In [165]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.5779816513761468

In [167]:
test = text_prepare('“อนุทิน” ขอ ผู้ร้อง เปิดชื่อ อักษรย่อ \"พ\" คนหักหัวคิวโรงแรม 40%')
#test = np.array([my_bag_of_words(test, WORDS_TO_INDEX, len(words_counts))])
test = tfidf_wordvec(vectorizer.transform([test]))
clf.predict(test)

array(['politics'], dtype='<U21')