# From Prev.
#Rearranged code
#Used ไทยรัฐฉบับพิมพ์ and ไทยรัฐออนไลน์ 460 data examples for train+test set
#Match Similar words manually (due to limited size of categories [hopefully :P])
#text = re.sub("[^ก-๙]", '', text) 73.04% with TFIDF
#text = re.sub("[^ก-ไ๐-๙]", '', text) ~72% with TFIDF
#used news_content instead of news_label, pretty fast

In [287]:
import pandas as pd
from urllib.parse import unquote

df = pd.read_json('data-1.json',encoding='utf-8')
#df.drop(['date','body','author','url'],axis=1,inplace=True) #for test_2.json
#df.drop(['id','news_content','date','url'],axis=1,inplace=True)

In [288]:
CAT= {
    #category: change to this
    'ข่าวบันเทิง':"entertainment",
    'regional':'local',
    'sport':'sports',
    'ข่าวกีฬา':'sports',
    'ข่าวอาชญากรรม':'crime',
    'khrongkhaidaasapparod':'ข่าวโครงข่ายตาสับปะรด',
    'around-the-world-news':'foreign',
    'abroad':'foreign',
    'ข่าวต่างประเทศ':'foreign',
    'ข่าวไลฟ์สไตล์':'lifestyle',
    'analysis-today-politics':'politics',
    'politic':'politics',
    'ข่าวเศรษฐกิจ':'economics',
    'economy':'economics',
    'economic':'economics',
    'uncategorized':'others',
    'auto':'car-vehicle',
    'thai-soccer':'thaifootball',
    'ข่าวพระราชสำนัก':'royalnews',
    'it':'tech'
}

In [289]:
def conv_cate(category):
    result = CAT.get(category,-1)
    if result!=-1:
        return result
    else :
        #in case want to update dictionary
        #CAT[category] = category
        return category

In [290]:
df['category'] = df['category'].apply(unquote).apply(conv_cate)

In [291]:
#tags cleaning
#df[df['category']=='1293427']
#df.drop([292],inplace=True)
df['category'].unique()
len(df['category'].unique())

53

In [292]:
df.isnull().sum()
#df.dropna().reset_index(drop=True)

id              0
news_topic      0
news_content    0
date            0
author          0
url             0
category        0
dtype: int64

In [293]:
import numpy as np
category = np.array(df['category'])
tags, freq = np.unique(category,return_counts=True)
freqList = list(zip(tags,freq))
freqList.sort(key=lambda elem:elem[1]) #sort by frequency
freqList[20:]

[('car-vehicle', 5),
 ('stock-monitor', 5),
 ('thaifootball', 6),
 ('covid-19', 7),
 ('index.php', 7),
 ('ข่าวโครงข่ายตาสับปะรด', 9),
 ('life', 10),
 ('women', 14),
 ('ข่าวในประเทศ', 14),
 ('bangkok', 15),
 ('bbc-thai', 18),
 ('trcheerthai', 18),
 ('special-stories', 20),
 ('society', 21),
 ('lifestyle', 22),
 ('tech', 22),
 ('breaking-news', 23),
 ('ข่าวด่วน', 23),
 ('pr-news', 28),
 ('news', 29),
 ('education', 30),
 ('others', 31),
 ('around-thailand', 32),
 ('business', 34),
 ('eurofootball', 78),
 ('crime', 80),
 ('economics', 96),
 ('article', 98),
 ('entertainment', 129),
 ('sports', 257),
 ('politics', 261),
 ('foreign', 338),
 ('local', 357)]

In [294]:
df['author'].unique()

array(['ch3', 'dailynews', 'khaosod', 'ไทยรัฐฉบับพิมพ์', 'ไทยรัฐออนไลน์'],
      dtype=object)

In [295]:
df[df['author']=='ไทยรัฐฉบับพิมพ์'].append(df[df['author']=='ไทยรัฐออนไลน์'])['category'].unique()

array(['local', 'business', 'news', 'foreign', 'life', 'politics',
       'society', 'food', 'others', 'trcheerthai', 'crime',
       'eurofootball', 'travel', 'car-vehicle', 'belief', 'worldcup',
       'volleyball', 'thaifootball', 'boxing-mma', 'tech'], dtype=object)

In [302]:
X = np.array(df[df['author']=='ไทยรัฐฉบับพิมพ์'].append(df[df['author']=='ไทยรัฐออนไลน์'])['news_content'])
y = np.array(df[df['author']=='ไทยรัฐฉบับพิมพ์'].append(df[df['author']=='ไทยรัฐออนไลน์'])['category'])

# Cleaning text


In [303]:
re.sub("[^ก-ไ๐-๙‘’“”]", '', 'ฟหกดเ้่าสาสงๆไำพัีนรนบลผปแอิืมทมใฝๅ/t/t_ภถุึคึre.sub("[^ก-ไ๐-๙‘’“”]"ฟหกดเ้่าสาสงๆไำพัีนรนบลผปแอิืมคตจจตช!!!')
#after searching thai ascii

'ฟหกดเาสาสงไำพัีนรนบลผปแอิืมทมใฝภถุึคึกไ๐๙‘’“”ฟหกดเาสาสงไำพัีนรนบลผปแอิืมคตจจตช'

In [304]:
import re
#prepare each sentence
def text_prepare(text):
    #text = re.sub("[/(){}\[\]\|@,;\n\t:\'\-!,'์'‘’“”]", '', text)
    #text = re.sub("[/\xa0]", '', text)
    #text = re.sub("[0-9]", '', text)
    text = re.sub("[^ก-๙‘’“”]", '', text)
    return text

In [305]:
#execute prepare
X = np.array([text_prepare(body) for body in X])


array(['นกหว้าชื่อภาษาอังกฤษเดิมทีเคยถูกจัดให้มีอยู่ด้วยกันชนิดแต่ปัจจุบันได้ถูกรวมกันเป็นชนิดเดียวกันนกหว้าชื่อภาษาอังกฤษเดิมทีเคยถูกจัดให้มีอยู่ด้วยกันชนิดแต่ปัจจุบันได้ถูกรวมกันเป็นชนิดเดียวกันใช้ชื่อวิทยาศาสตร์ว่าตั้งโดยคาโรลัสลินเนียสตามชื่ออากัสยักษ์ร้อยตาในเทพปกรณัมกรีกเพราะบนปีกมีลายจุดคล้ายตาเป็นจำนวนมากจัดเป็นสัตว์ในกลุ่มไก่ฟ้าขนาดใหญ่มีขนสีน้ำตาลหัวและคอเป็นสีฟ้ามักพบในป่าของเกาะบอเนียวเกาะสุมาตราและคาบสมุทรมลายูจัดเป็นสัตว์ในกลุ่มไก่ฟ้าขนาดใหญ่มีขนสีน้ำตาลหัวและคอเป็นสีฟ้ามักพบในป่าของเกาะบอเนียวเกาะสุมาตราและคาบสมุทรมลายูส่วนในบ้านเราถือว่ามีขนาดใหญ่ที่สุดพบอาศัยอยู่ในป่าดิบชื้นทางภาคใต้ผู้คนที่ไปเที่ยวป่ามักจะได้ยินเสียงร้องดังกังวานมากกว่าจะได้เห็นตัวจริงเนื่องจากเป็นนกที่ขี้อายเดินได้เงียบเชียบและเปรียวมากมักจะหนีไปล่วงหน้าก่อนที่เราจะเข้าใกล้นกหว้าตัวผู้จะมีขนปีกยาวและมีลวดลายโดดเด่นเป็นเอกลักษณ์มากกว่าตัวเมียเลยถูกขนานนามว่าเป็นพญาระกาหรือเจ้าแห่งไก่นกหว้าตัวผู้จะมีขนปีกยาวและมีลวดลายโดดเด่นเป็นเอกลักษณ์มากกว่าตัวเมียเลยถูกขนานนามว่าเป็นพญาระกาหรือเจ้าแห่งไก่เมื่อเข้า

# Prepare train and test set

In [306]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [307]:
type(X_train)

numpy.ndarray

In [308]:
len(X_test)

115

## Check tag distribution

In [ ]:
#not well distributed
tags, freq = np.unique(y_train,return_counts=True)
list(zip(tags,freq))

# Tokenize thai words

In [309]:
from pythainlp.tokenize import word_tokenize

In [310]:

#tokenize function
def Thaitokenize(text):
    """
    turn a Thai sentence into Thai words with meaning
    """
    text = ''.join(text.split('"')) ##handled in regex??
    text = word_tokenize(text , engine = 'pyicu')
    return text

In [ ]:
#try mapping function
#Error
#list(map(Thaitokenize,X_train))

In [311]:
Thaitokenize('""แสนสิริ""สร้างUN Global Standards of Conduct for Business\xa0')

['แสน',
 'สิริ',
 'สร้าง',
 'UN',
 ' ',
 'Global',
 ' ',
 'Standards',
 ' ',
 'of',
 ' ',
 'Conduct',
 ' ',
 'for',
 ' ',
 'Business',
 '\xa0']

### just a test for fun###
%timeit word_tokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียม' , engine = 'pyicu')

### just a test for fun###
%timeit word_tokenize('แสนสิริสร้างมาตรฐานใหม่ของการยอมรับความเท่าเทียม' , engine = 'newmm')

In [271]:
#words to account in the bag
words_counts = {}

for i in X_train: #each i is a topic sentence
    wordlist = Thaitokenize(i)
    for j in wordlist:
        words_counts[j] = words_counts.get(j,0) + 1
#words_counts = 238

WORDS_TO_INDEX = dict(zip(words_counts.keys(),list(x for x in range(len(words_counts)))))

In [ ]:
len(words_counts)

# Create bag of words

In [ ]:
#create a bag of words for a sentence
def my_bag_of_words(text, words_to_index, dict_size):
    """
        text: a sentence
        words_to_index: words to count in the bag 
        e.g.
        words_to_index = {'hi': 0, 'you': 1, 'me': 2, 'are': 3}
        
        dict_size: size of the dictionary
        
        return a vector which is a bag-of-words representation of 'text'
    """
    result_vector = np.zeros(dict_size)
    
    #tokenize Thai words
    words = Thaitokenize(text)
    
    for i in words:
      if(words_to_index.get(i,-1)!=-1) :
        result_vector[words_to_index[i]]=+1
    return result_vector

In [ ]:
#X_train_my_bag = np.array([my_bag_of_words(text, WORDS_TO_INDEX, len(words_counts)) for text in X_train])

# TFIDF

In [312]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [ ]:
#X_train_tfidf = vectorizer.fit_transform(X_train)
#print(vectorizer.get_feature_names())
#print(X.shape)

In [313]:
vectorizer = TfidfVectorizer(tokenizer=Thaitokenize, max_df=0.9, min_df = 5)
#vectorizer = TfidfVectorizer(tokenizer=Thaitokenize, max_df=0.9, min_df = 0)
#max_df=0.8, min_df=5 not much difference
#vectorizer = TfidfVectorizer(tokenizer=Thaitokenize, max_df=0.8, min_df = 10)
X_train_tfidf = vectorizer.fit_transform(X_train)
print(vectorizer.get_feature_names())
print(X_train_tfidf.shape)

['ก', 'กก', 'กค', 'กซ์', 'กฎหมาย', 'กด', 'กดดัน', 'กทม', 'กน', 'กนก', 'กบฏ', 'กพ', 'กม', 'กย', 'กร', 'กรกฎาคม', 'กรณี', 'กรม', 'กรมอุตุนิยมวิทยา', 'กรรม', 'กรรมการ', 'กรรมาธิการ', 'กรอง', 'กรอบ', 'กระ', 'กระจก', 'กระจาย', 'กระดูก', 'กระตุ้น', 'กระทบ', 'กระทรวง', 'กระทรวงกลาโหม', 'กระทรวงการคลัง', 'กระทรวงคมนาคม', 'กระทรวงมหาดไทย', 'กระทรวงสาธารณสุข', 'กระทรวงเกษตรและสหกรณ์', 'กระทั่ง', 'กระบวนการ', 'กระบะ', 'กระบี่', 'กระเด็น', 'กระแส', 'กระแสข่าว', 'กราย', 'กรุง', 'กรุงเทพมหานคร', 'กรุงเทพฯ', 'กร้าว', 'กลับ', 'กลับบ้าน', 'กลับมา', 'กลัว', 'กลาง', 'กลายเป็น', 'กลุ่ม', 'กลุ่มคน', 'กลไก', 'กล่าว', 'กล่าวถึง', 'กล่าวว่า', 'กล่าวหา', 'กล้อง', 'กล้องวงจรปิด', 'กล้า', 'กว่า', 'กสภ', 'กอ', 'กอง', 'กองกลาง', 'กองกำลัง', 'กองทัพ', 'กองทุน', 'กองหน้า', 'กองหลัง', 'กอบ', 'กะทันหัน', 'กัก', 'กักตัว', 'กังวล', 'กัน', 'กันที่', 'กันยายน', 'กันเอง', 'กับ', 'กัปตัน', 'กั้น', 'กา', 'กาญจนบุรี', 'การ', 'การกระทำ', 'การกีฬาแห่งประเทศไทย', 'การควบคุม', 'การคาดการณ์', 'การค้า', 'การงาน', 'การจราจร', 'การตล

In [ ]:
#[word for word in WORDS_TO_INDEX]
#type(WORDS_TO_INDEX.keys())
#X_train_tfidf

##ARRAY <-> Sparse matrix much faster
#X_train_tfidf.toarray() 
#sparse matrix to array
#from scipy import sparse
#sparse.csr_matrix(X_train_tfidf.toarray()) 
#array to sparse matrix

In [ ]:
#for illustration & checking
featurelist = vectorizer.get_feature_names()
TFIDF = pd.DataFrame(X_train_tfidf.toarray(),columns = featurelist)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
TFIDF


In [314]:
X_train_tfidf

<344x2700 sparse matrix of type '<class 'numpy.float64'>'
	with 52197 stored elements in Compressed Sparse Row format>

# turn y values to 1s,0s

In [ ]:
# from sklearn.preprocessing import MultiLabelBinarizer
# this is for list of tags

In [ ]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
#lb.fit_transform([1, 2, 6, 4, 2]) 
#fit & transform in one step
#fit = figure out different classes and turn into necessary binary formats
#transform = transform given data into binary formats

In [ ]:
y_train_lb = lb.fit_transform(y_train)


In [ ]:
lb.classes_.size

In [ ]:
#for illustration & checking
Y_LB = pd.DataFrame(y_train_lb,columns = lb.classes_)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
Y_LB.iloc[10:20]
#y_train.iloc[10:20]

In [ ]:
y_train_lb.shape

# Train model to predict tags

In [315]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
#example
X = np.array([
     [10, 10],
     [8, 10],
     [-5, 5.5],
     [-5.4, 5.5],
     [-20, -20],
     [-15, -20]])
y = np.array([0, 0, 1, 1, 2, 2])
clf = OneVsRestClassifier(SVC()).fit(X, y)
clf.predict([[-19, -20], [9, 9], [-5, 5]])

array([2, 0, 1])

In [316]:
clf = OneVsRestClassifier(SVC()).fit(X_train_tfidf, y_train)

In [317]:
y_train

array(['news', 'business', 'car-vehicle', 'society', 'eurofootball',
       'others', 'local', 'foreign', 'others', 'eurofootball', 'foreign',
       'eurofootball', 'politics', 'business', 'politics', 'foreign',
       'foreign', 'foreign', 'politics', 'society', 'thaifootball',
       'eurofootball', 'local', 'local', 'others', 'politics',
       'thaifootball', 'boxing-mma', 'life', 'politics', 'trcheerthai',
       'foreign', 'business', 'foreign', 'foreign', 'eurofootball',
       'others', 'news', 'eurofootball', 'local', 'business', 'news',
       'politics', 'politics', 'politics', 'politics', 'politics',
       'politics', 'society', 'local', 'local', 'trcheerthai', 'business',
       'eurofootball', 'local', 'politics', 'crime', 'eurofootball',
       'eurofootball', 'foreign', 'foreign', 'business', 'society',
       'news', 'others', 'eurofootball', 'eurofootball', 'news', 'local',
       'others', 'society', 'foreign', 'politics', 'car-vehicle',
       'foreign', 'local', 

In [318]:
#check the predictions, models applied correctly? Yes
y = clf.predict(X_train_tfidf)
print(np.concatenate((y.reshape(len(y),1), y_train.reshape(len(y_train),1)),1))

[['news' 'news']
 ['business' 'business']
 ['car-vehicle' 'car-vehicle']
 ['society' 'society']
 ['eurofootball' 'eurofootball']
 ['others' 'others']
 ['local' 'local']
 ['foreign' 'foreign']
 ['others' 'others']
 ['eurofootball' 'eurofootball']
 ['foreign' 'foreign']
 ['eurofootball' 'eurofootball']
 ['politics' 'politics']
 ['business' 'business']
 ['politics' 'politics']
 ['foreign' 'foreign']
 ['foreign' 'foreign']
 ['foreign' 'foreign']
 ['politics' 'politics']
 ['society' 'society']
 ['thaifootball' 'thaifootball']
 ['eurofootball' 'eurofootball']
 ['local' 'local']
 ['local' 'local']
 ['others' 'others']
 ['politics' 'politics']
 ['thaifootball' 'thaifootball']
 ['boxing-mma' 'boxing-mma']
 ['life' 'life']
 ['politics' 'politics']
 ['trcheerthai' 'trcheerthai']
 ['foreign' 'foreign']
 ['business' 'business']
 ['foreign' 'foreign']
 ['foreign' 'foreign']
 ['eurofootball' 'eurofootball']
 ['others' 'others']
 ['news' 'news']
 ['eurofootball' 'eurofootball']
 ['local' 'local']
 ['b

In [319]:
X_test = np.array([text_prepare(title) for title in X_test])
#X_test_my_bag = np.array([my_bag_of_words(text, WORDS_TO_INDEX, len(words_counts)) for text in X_test])
X_test_tfidf = vectorizer.transform(X_test)
y_pred = clf.predict(X_test_tfidf)
y_test = np.array(y_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#print(np.concatenate(y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1),1))

[['local' 'local']
 ['eurofootball' 'worldcup']
 ['foreign' 'foreign']
 ['news' 'news']
 ['trcheerthai' 'trcheerthai']
 ['local' 'local']
 ['eurofootball' 'eurofootball']
 ['foreign' 'foreign']
 ['foreign' 'others']
 ['local' 'local']
 ['eurofootball' 'eurofootball']
 ['local' 'local']
 ['business' 'business']
 ['foreign' 'foreign']
 ['foreign' 'foreign']
 ['foreign' 'foreign']
 ['foreign' 'foreign']
 ['eurofootball' 'eurofootball']
 ['local' 'belief']
 ['foreign' 'others']
 ['business' 'business']
 ['local' 'local']
 ['business' 'crime']
 ['others' 'others']
 ['local' 'local']
 ['politics' 'politics']
 ['local' 'local']
 ['foreign' 'foreign']
 ['eurofootball' 'life']
 ['others' 'volleyball']
 ['foreign' 'foreign']
 ['local' 'society']
 ['others' 'others']
 ['eurofootball' 'thaifootball']
 ['eurofootball' 'eurofootball']
 ['eurofootball' 'eurofootball']
 ['eurofootball' 'eurofootball']
 ['local' 'society']
 ['eurofootball' 'eurofootball']
 ['others' 'others']
 ['eurofootball' 'eurofoot

In [320]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  2  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 18  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0

0.7304347826086957

In [321]:
test = text_prepare('“อนุทิน” ขอ ผู้ร้อง เปิดชื่อ อักษรย่อ \"พ\" คนหักหัวคิวโรงแรม 40%')
#test = np.array([my_bag_of_words(test, WORDS_TO_INDEX, len(words_counts))])
test = vectorizer.transform([test])
clf.predict(test)

array(['local'], dtype='<U12')